import {Injectable} from '@angular/core';
import {AutoCompleteService} from 'ionic4-auto-complete';

@Injectable({
    providedIn: 'root'
  })

export class SuggestService implements AutoCompleteService {
  labelAttribute = 'name';
  public objects:any[] = [
    {
      name:'Milano',
      zona:8
    },
    {
      name:'San Donato M3',
      zona:90
    },
    {name:'Cascina Gobba M2'},
    {name:'Sesto Marelli M1'},
    {name:'Rho Fiera Milano M1'},
    {name:'Linate Aereoporto'},
    {name:'Monza Bettola'},   
    {name:'Abbiategrasso'},
    {name:'Agrate Brianza'},
    {name:'Aicurzio'},
    {name:'Albairate'},
    {name:'Albiate'},
    {name:'Arconate'},
    {name:'Arcore'},
    {name:'Arese'},
    {name:'Arluno'},
    {name:'Assago'},
    {name:'Baranzate'},
    {name:'Bareggio'},
    {name:'Barlassina'},
    {name:'Basiano'},
    {name:'Basiglio'},
    {name:'Bellinzago Lombardo'},
    {name:'Bellusco'},
    {name:'Bernareggio'},
    {name:'Bernate Ticino'},
    {name:'Besana in Brianza'},
    {name:'Besate'},
    {name:'Biassono'},
    {name:'Binasco'},
    {name:'Boffalora sopra Ticino'},
    {name:'Bollate'},
    {name:'Bovisio-Masciago'},
    {name:'Bregnano'},
    {name:'Bresso'},
    {name:'Briosco'},
    {name:'Brugherio'},
    {name:'Bubbiano'},
    {name:'Buccinasco'},
    {name:'Burago di Molgora'},
    {name:'Buscate'},
    {name:'Busnago'},
    {name:'Bussero'},
    {name:'Busto Arsizio'},
    {name:'Busto Garolfo'},
    {name:'Cabiate'},
    {name:'Calusco d\'Adda'},
    {name:'Calvignasco'},
    {name:'Cambiago'},
    {name:'Camparada'},
    {name:'Canegrate'},
    {name:'Cantù'},
    {name:'Caponago'},
    {name:'Carate Brianza'},
    {name:'Carimate'},
    {name:'Carnate'},
    {name:'Caronno Pertusella'},
    {name:'Carpiano'},
    {name:'Carugate'},
    {name:'Casalmaiocco'},
    {name:'Casarile'},
    {name:'Casatenovo'},
    {name:'Casorate Primo'},
    {name:'Casorezzo'},
    {name:'Cassano d\'Adda'},
    {name:'Cassina de\' Pecchi'},
    {name:'Cassinetta di Lugagnano'},
    {name:'Castano Primo'},
    {name:'Castellanza'},
    {name:'Cavenago di Brianza'},
    {name:'Ceriano Laghetto'},
    {name:'Cermenate'},
    {name:'Cernusco Lombardone'},
    {name:'Cernusco sul Naviglio'},
    {name:'Cerro al Lambro'},
    {name:'Cerro Maggiore'},
    {name:'Cesano Boscone'},
    {name:'Cesano Maderno'},
    {name:'Cesate'},
    {name:'Cinisello Balsamo'},
    {name:'Cisliano'},
    {name:'Cogliate'},
    {name:'Cologno Monzese'},
    {name:'Colturano'},
    {name:'Comazzo'},
    {name:'Concorezzo'},
    {name:'Corbetta'},
    {name:'Cormano'},
    {name:'Cornaredo'},
    {name:'Cornate d\'Adda'},
    {name:'Correzzana'},
    {name:'Corsico'},
    {name:'Cuggiono'},
    {name:'Cusago'},
    {name:'Cusano Milanino'},
    {name:'Dairago'},
    {name:'Desio'},
    {name:'Dresano'},
    {name:'Figino Serenza'},
    {name:'Gaggiano'},
    {name:'Garbagnate Milanese'},
    {name:'Gessate'},
    {name:'Giussano'},
    {name:'Gorgonzola'},
    {name:'Grezzago'},
    {name:'Gudo Visconti'},
    {name:'Inveruno'},
    {name:'Inzago'},
    {name:'Lacchiarella'},
    {name:'Lainate'},
    {name:'Lazzate'},
    {name:'Legnano'},
    {name:'Lentate sul Seveso'},
    {name:'Lesmo'},
    {name:'Limbiate'},
    {name:'Liscate'},
    {name:'Lissone'},
    {name:'Locate di Triulzi'},
    {name:'Macherio'},
    {name:'Magenta'},
    {name:'Magnago'},
    {name:'Marcallo con Casone'},
    {name:'Mariano Comense'},
    {name:'Masate'},
    {name:'Meda'},
    {name:'Mediglia'},
    {name:'Melegnano'},
    {name:'Melzo'},
    {name:'Merate'},
    {name:'Merlino'},
    {name:'Mesero'},
    {name:'Mezzago'},
    {name:'Misinto'},
    {name:'Monticello Brianza'},
    {name:'Monza'},
    {name:'Morimondo'},
    {name:'Motta Visconti'},
    {name:'Muggiò'},
    {name:'Mulazzano'},
    {name:'Nerviano'},
    {name:'Nosate'},
    {name:'Nova Milanese'},
    {name:'Novate Milanese'},
    {name:'Novedrate'},
    {name:'Noviglio'},
    {name:'Olgiate Molgora'},
    {name:'Opera'},
    {name:'Origgio'},
    {name:'Ornago'},
    {name:'Osnago'},
    {name:'Ossona'},
    {name:'Ozzero'},
    {name:'Paderno d\'Adda'},
    {name:'Paderno Dugnano'},
    {name:'Pantigliate'},
    {name:'Parabiago'},
    {name:'Paullo'},
    {name:'Pero'},
    {name:'Peschiera Borromeo'},
    {name:'Pessano con Bornago'},
    {name:'Pieve Emanuele'},
    {name:'Pioltello'},
    {name:'Pogliano Milanese'},
    {name:'Pozzo d\'Adda'},
    {name:'Pozzuolo Martesana'},
    {name:'Pregnana Milanese'},
    {name:'Renate'},
    {name:'Rescaldina'},
    {name:'Rho'},
    {name:'Robbiate'},
    {name:'Robecchetto con Induno'},
    {name:'Robecco sul Naviglio'},
    {name:'Rodano'},
    {name:'Roncello'},
    {name:'Ronco Briantino'},
    {name:'Rosate'},
    {name:'Rovellasca'},
    {name:'Rozzano'},
    {name:'San Donato Milanese'},
    {name:'San Giorgio su Legnano'},
    {name:'San Giuliano Milanese'},
    {name:'Santo Stefano Ticino'},
    {name:'San Vittore Olona'},
    {name:'San Zenone al Lambro'},
    {name:'Saronno'},
    {name:'Sedriano'},
    {name:'Segrate'},
    {name:'Senago'},
    {name:'Seregno'},
    {name:'Sesto San Giovanni'},
    {name:'Settala'},
    {name:'Settimo Milanese'},
    {name:'Seveso'},
    {name:'Solaro'},
    {name:'Sordio'},
    {name:'Sovico'},
    {name:'Sulbiate'},
    {name:'Tavazzano con Villavesco'},
    {name:'Treviglio'},
    {name:'Trezzano Rosa'},
    {name:'Trezzano sul Naviglio'},
    {name:'Trezzo sull\'Adda'},
    {name:'Tribiano'},
    {name:'Triuggio'},
    {name:'Truccazzano'},
    {name:'Turbigo'},
    {name:'Uboldo'},
    {name:'Usmate Velate'},
    {name:'Vanzaghello'},
    {name:'Vanzago'},
    {name:'Vaprio d\'Adda'},
    {name:'Varedo'},
    {name:'Vedano al Lambro'},
    {name:'Veduggio con Colzano'},
    {name:'Verano Brianza'},
    {name:'Verderio'},
    {name:'Vermezzo'},
    {name:'Vernate'},
    {name:'Vignate'},
    {name:'Villa Cortese'},
    {name:'Villasanta'},
    {name:'Vimercate'},
    {name:'Vimodrone'},
    {name:'Vittuone'},
    {name:'Vizzolo Predabissi'},
    {name:'Zelo Buon Persico'},
    {name:'Zelo Surrigone'},
    {name:'Zibido San Giacomo'}
    
  ];

  constructor() {
      
  }

  getResults(keyword) {
    keyword = keyword.toLowerCase();

    return this.objects.filter(
      (object) => {
         const value = object[this.labelAttribute].toLowerCase();

         return value.includes(keyword);
      }
    );
  }
}
